- hosts: all
  remote_user: azureuser
  become: true
  gather_facts: yes
   
  tasks:
    - name: Update all packeges
      apt:
        update_cache: yes
        name: "*"
        state: latest

    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"    

    - name: Install dependencies
      apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg2
          - lsb-release
          - htop
          - wget
          - git
          - mc
          - python3-pip
          - net-tools

    - name: Install apt key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present 
        keyring: /etc/apt/trusted.gpg.d/docker.gpg  
    
    - name: Add Percona repo  
      apt:
        deb: https://repo.percona.com/apt/percona-release_latest.{{ ansible_distribution_release }}_all.deb

    - name: Set Percona distributive
      shell: percona-release setup ps80     

    - name: Install Percona 8.0
      apt: name=percona-server-server state=present update_cache=yes  

    - name: Copy conf file  
      template: 
        src: templates/mysqld.cnf.j2
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        owner: root
        group: root
        mode: 0644

    - name: Restart DB
      systemd: 
        name: mysql
        state: restarted         